### ISSUE TITLE
[Bug] Potential XSS vulnerability

### ISSUE THREAD

**Issue by OmTheTurtle** [CreativeBulma/bulma-tagsinput#17]
Hi,

I'm using tagsinput in one of my projects and noticed the following: If I write some JS code between script tags into the input (e.g. ` <script>alert('1')</script>`), it gets ran, and after that the input displays an empty item:

![image](https://user-images.githubusercontent.com/34893944/94667339-03518900-030f-11eb-9adb-ac5bf57bcefc.png)

The script also runs every time I preload the tagsinput with the script tag.

**Comment by CreativeBulma** [comment]
hi,

did you update to the last version released this week? it integrates a fix for this kind of vulnerabilities.

regards,

**Comment by OmTheTurtle** [comment]
Hi,

yes, it turns around that I didn't update the CDN URL. Thanks.
